In [2]:
import numpy as np
import pandas as pd
from IPython.display import display

In [3]:
# -------------------Loading the data ---------------------- #

# TO LOAD A CSV FILE IN PANDAS ---> pd.read_csv('file.csv') || file.csv----> is path of that file

# Currently anime.csv is in the same folder so we just write anime.csv

df = pd.read_csv('anime.csv')
display(df)

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [4]:
#----------------ONLY VIEW FIRST 5 ROWS-------------------#

df.head() # function to view top 5 rows ..

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [5]:
#---------------------QUESTI0NS----------------------#

# 1--> make a new column for episode count
# 2--> make a new column for time stamp
# 3--> which anime has the highest score
# 4--> give me top 5 highest scoring anime
# 5--> which anime has the highest episode count
# 6--> animes with top 5 episode count
# 7--> which is the longest running anime

In [6]:
#----------------------------------------Q:1------------------------------------------------------#

#----------------WHAT IS FEATURE EXTRACTION--------------#

# NOW , here we can see there are many analytics based on episode count so 
# why not make a column for episode count itself as it is used directly
# but there is no feature for episode count so we need to extract it from title which has ep count indirectly
# this is called feature extraction , as we onoy have 3 features right now for analytics rank , title ,score

In [7]:

#---------------PATTERN---------------#

display(df.loc[1]) # we only need title to extract out feature 'ep count' 
print("\nTitle format : ")
display(df.loc[1]['Title'])

print("\nTitle format : ")
display(df.loc[3]['Title'])

print("\nTitle format : ")
display(df.loc[45]['Title'])

# notice the format episode count is always in brackets ..

Rank                                                     2
Title    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
Score                                                 9.07
Name: 1, dtype: object

Title format :

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

Title format :

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

Title format :

'Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview'

In [8]:
#------------EXTRACTION FUNCTION DEBUGGING-------------#

def extract_episode_count(title):
    
    start = title.find('(')
    end   = title.find(' eps)')
    print(f"\nstart : {start}, end : {end} ")
          
    # slice the string :
    number_part_title_as_string = title[start:end]
    print("extracted part as a string :" ,number_part_title_as_string)

    # corrected slicing :
    number_part_title_as_string = title[start+1:end]
    print("corrected extracted part as a string   : ",number_part_title_as_string, type(number_part_title_as_string))

    # convert it into integer : 
    count_episode = int(number_part_title_as_string)
    print("corrected extracted part as an integer : ",count_episode,type(count_episode))

    return count_episode


# Test it manually before parsing
print("\nEpisode count = " , extract_episode_count(df.loc[1]['Title']))
print("\nEpisode count = " , extract_episode_count(df.loc[2]['Title']))
print("\nEpisode count = " , extract_episode_count(df.loc[3]['Title']))
print("\nEpisode count = " , extract_episode_count(df.loc[33]['Title']))
print("\nEpisode count = " , extract_episode_count(df.loc[10]['Title']))
print("\nEpisode count = " , extract_episode_count(df.loc[12]['Title']))
print("\nEpisode count = " , extract_episode_count(df.loc[45]['Title']))

start : 14, end : 17
extracted part as a string : (24
corrected extracted part as a string   :  24 <class 'str'>
corrected extracted part as an integer :  24 <class 'int'>

Episode count =  24

start : 28, end : 31
extracted part as a string : (13
corrected extracted part as a string   :  13 <class 'str'>
corrected extracted part as an integer :  13 <class 'int'>

Episode count =  13

start : 11, end : 14
extracted part as a string : (51
corrected extracted part as a string   :  51 <class 'str'>
corrected extracted part as an integer :  51 <class 'int'>

Episode count =  51

start : 20, end : 23
extracted part as a string : (13
corrected extracted part as a string   :  13 <class 'str'>
corrected extracted part as an integer :  13 <class 'int'>

Episode count =  13

start : 59, end : 61
extracted part as a string : (2
corrected extracted part as a string   :  2 <class 'str'>
corrected extracted part as an integer :  2 <class 'int'>

Episode count =  2

start : 45, end : 48
extracted part as a string : (13
corrected extracted part as a string   :  13 <class 'str'>
corrected extracted part as an integer :  13 <class 'int'>

Episode count =  13

start : 15, end : 18
extracted part as a string : (24
corrected extracted part as a string   :  24 <class 'str'>
corrected extracted part as an integer :  24 <class 'int'>

Episode count =  24

In [9]:
#------------------TESTING A NEW COLUMN NOW AS FUNCTION TO APPLY WORKS--------------#

# Now function is working so to apply that function we use df.apply

# To avoid multiple lines printing for every call we ENHANCE THE EXISTING FUNCTION so nothing gets printed

def extract_episode_count(title):
    start = title.find('(')
    end = title.find(' eps)')

    if (start==(-1)) or (end==(-1)) :
        return None
    
    count_part = title[start+1:end]

    return int(count_part)
    
df['Episode_Count'] = df['Title'].apply(extract_episode_count)

display(df.head())

df.info() 
# we can see for every 50 episode ep_count has datatype integer(int64) and non null ,
# so NO NULL VALUES of episode_count to replace for any title ...

,Rank,Title,Score,Episode_Count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           50 non-null     int64
 1   Title          50 non-null     object
 2   Score          50 non-null     float64
 3   Episode_Count  50 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.7+ KB

In [10]:
# --------VIEW FIRST 20 ROWS TO CHECK IF FEATURE EXTRACTION WORKED----------#

threshold  = np.arange(0,20)
display(threshold)

display(df.loc[threshold])

df.info()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

,Rank,Title,Score,Episode_Count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           50 non-null     int64
 1   Title          50 non-null     object
 2   Score          50 non-null     float64
 3   Episode_Count  50 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.7+ KB

In [11]:
#----------VIEWING WHOLE DATAFRAME ------------#
display(df)

,Rank,Title,Score,Episode_Count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4

In [12]:

#-------------------------------------Q:2-------------------------------------------#

In [13]:
#-----------UNDERSTANDING PATTERN------------#

# MAKE A NEW COLUMN FOR TIMESTAMP

display(df.loc[[1,2,3]]['Title'])

# Not able to view full title texts so set the limit to none by using a new function

pd.set_option('display.max_colwidth',None)

display(df.loc[[1,2,3,33,44,24,37]]['Title'])

# We can see start date starts after ) everytime and ends before '-' (dash) so lets extract start first

1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
Name: Title, dtype: object

1                 Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members
2     Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members
3                      Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members
33          Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members
44            Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members
24                    MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members
37                 "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,856 members
Name: Title, dtype: object

In [14]:
#-----------------START DATE EXTRACTION DEBUGGING----------#

def get_start_month(title):

    start = title.find(')')
    end   = title.find(' members')

    print("\nStart Index : ",start)
    print("End Index   : ", end)

    start_timestamp = title[start:end]

    print("Extracted start date           : ",start_timestamp)

    # corrected part now : 
    start_timestamp = title[start+1:end]
    print("Corrected Extracted start date : ",start_timestamp,type(start_timestamp))
    

    # removing trailing/leading spaces 
    start_timestamp = start_timestamp.strip()

    parts = start_timestamp.split(' ')
    print(parts)
    
    start_month = parts[0]
    start_year  = int(parts[1])
    print("Start Month : ", start_month , type(start_month))
    print("Start Year  : ",start_year , type(start_year))

    return start_month
    
# Test it manually....
df.loc[[1,2,30,41,17]]['Title'].apply(get_start_month)

Start Index :  21
End Index   :  50
Extracted start date           :  )Apr 2011 - Sep 20112,473,707
Corrected Extracted start date :  Apr 2011 - Sep 20112,473,707 <class 'str'>
['Apr', '2011', '-', 'Sep', '20112,473,707']
Start Month :  Apr <class 'str'>
Start Year  :  2011 <class 'int'>

Start Index :  35
End Index   :  62
Extracted start date           :  )Oct 2022 - Dec 2022474,138
Corrected Extracted start date :  Oct 2022 - Dec 2022474,138 <class 'str'>
['Oct', '2022', '-', 'Dec', '2022474,138']
Start Month :  Oct <class 'str'>
Start Year  :  2022 <class 'int'>

Start Index :  35
End Index   :  63
Extracted start date           :  )Jul 2023 - Aug 2023 556,301
Corrected Extracted start date :  Jul 2023 - Aug 2023 556,301 <class 'str'>
['Jul', '2023', '-', 'Aug', '2023', '556,301']
Start Month :  Jul <class 'str'>
Start Year  :  2023 <class 'int'>

Start Index :  53
End Index   :  82
Extracted start date           :  )Jan 2022 - Apr 20221,170,165
Corrected Extracted start date :  Jan 2022 - Apr 20221,170,165 <class 'str'>
['Jan', '2022', '-', 'Apr', '20221,170,165']
Start Month :  Jan <class 'str'>
Start Year  :  2022 <class 'int'>

Start Index :  36
End Index   :  63
Extracted start date           :  )Oct 2017 - Mar 2018388,358
Corrected Extracted start date :  Oct 2017 - Mar 2018388,358 <class 'str'>
['Oct', '2017', '-', 'Mar', '2018388,358']
Start Month :  Oct <class 'str'>
Start Year  :  2017 <class 'int'>

1     Apr
2     Oct
30    Jul
41    Jan
17    Oct
Name: Title, dtype: object

In [15]:
#------------------------------CREATING START MONTH COLUMN----------------#

#-----CREATING NEW FUNCITON REMOVING PRINTED LINES USED FOR DEBUGGING-----#


def get_start_month(title):
    
    start = title.find(')')
    end   = title.find(' members')
    

    start_timestamp = title[start+1:end]

    start_timestamp = start_timestamp.strip() # removing leading trailing spaces..

    parts = start_timestamp.split(' ')
    
    start_month = parts[0]
    start_year  = parts[1]

    return start_month

df['Start_Month'] = df['Title'].apply(get_start_month)

In [16]:
#----------VIEWING TOP 20 ROWS TO VERIFY-------------#

threshold = np.arange(0,20)
display(df.head())
display(df.info())
display(df.loc[threshold])

,Rank,Title,Score,Episode_Count,Start_Month
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,64,Apr
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24,Apr
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,13,Oct
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,51,Apr
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,10,Apr

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           50 non-null     int64
 1   Title          50 non-null     object
 2   Score          50 non-null     float64
 3   Episode_Count  50 non-null     int64
 4   Start_Month    50 non-null     object
dtypes: float64(1), int64(2), object(2)
memory usage: 2.1+ KB

None

,Rank,Title,Score,Episode_Count,Start_Month
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,64,Apr
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24,Apr
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,13,Oct
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,51,Apr
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,10,Apr
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,51,Apr
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,1,Jan
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,148,Oct
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,13,Apr
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,13,Oct
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,2,Mar
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,110,Jan
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,13,Jul
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,13,Apr
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,12,Jan
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,201,Apr
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,1,Sep
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,22,Oct
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,24,Oct
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,25,Apr

In [17]:
#---------------------START YEAR COLUMN TO ADD-----------------------------#

def get_start_year(title):
    
    start = title.find(')')
    end   = title.find(' members')
    

    start_timestamp = title[start+1:end]

    start_timestamp = start_timestamp.strip() # removing leading trailing spaces..

    parts = start_timestamp.split(' ')
    
    start_month = parts[0]
    start_year  = parts[1]

    return start_year 

display(df.loc[[1,14,38,42]]['Title'].apply(get_start_year))
display(df.loc[[1,14,38,42]]['Title'])

1     2011
14    2017
38    2016
42    2000
Name: Title, dtype: object

1                                                   Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members
14                                                       Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members
38    Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members
42                                                 Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members
Name: Title, dtype: object

In [18]:
#---------VIEWING FIRST 20 ROWS TO VERIFY------------#

df['Start_Year'] = df['Title'].apply(get_start_year)
threshold = np.arange(0,20)
display(df.loc[threshold])

,Rank,Title,Score,Episode_Count,Start_Month,Start_Year
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,64,Apr,2009
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24,Apr,2011
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,13,Oct,2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,51,Apr,2015
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,10,Apr,2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,51,Apr,2011
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,1,Jan,2021
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,148,Oct,2011
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,13,Apr,2022
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,13,Oct,2012
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,2,Mar,2023
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,110,Jan,1988
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,13,Jul,2023
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,13,Apr,2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,12,Jan,2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,201,Apr,2006
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,1,Sep,2016
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,22,Oct,2017
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,24,Oct,2008
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,25,Apr,2008

In [19]:
#----------VIEWING ALL------------#

display(df)

,Rank,Title,Score,Episode_Count,Start_Month,Start_Year
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,64,Apr,2009
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24,Apr,2011
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,13,Oct,2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,51,Apr,2015
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,10,Apr,2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,51,Apr,2011
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,1,Jan,2021
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,148,Oct,2011
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,13,Apr,2022
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,13,Oct,2012
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,2,Mar,2023
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,110,Jan,1988
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,13,Jul,2023
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,13,Apr,2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,12,Jan,2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,201,Apr,2006
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,1,Sep,2016
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,22,Oct,2017
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,24,Oct,2008
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,25,Apr,2008
20,21,"Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie (1 eps)Jul 2013 - Jul 2013232,388 members",8.91,1,Jul,2013
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89,1,Sep,2020
22,23,"Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 - Aug 2017385,248 members",8.88,7,Aug,2017
23,24,"Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV (14 eps)Jul 2018 - Oct 2018189,172 members",8.88,14,Jul,2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87,74,Apr,2004
25,26,"Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 20162,635,814 membersManga StoreVolume 1€4.58Preview",8.84,1,Aug,2016
26,27,"Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie (1 eps)Dec 2022 - Dec 2022205,150 members",8.84,1,Dec,2022
27,28,"Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022464,981 members",8.83,12,Oct,2022
28,29,"The First Slam DunkMovie (1 eps)Dec 2022 - Dec 202227,063 members",8.83,1,Dec,2022
29,30,"Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun 2023495,454 membersManga StoreVolume 1€17.99Preview",8.82,24,Jan,2023
30,31,"Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 - Aug 2023 556,301 members",8.82,23,Jul,2023
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81,12,Jan,2018
32,33,"Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 202193,645 members",8.81,26,Apr,2020
33,34,"Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members",8.80,13,Jan,2019
34,35,"Shingeki no Kyojin: The Final SeasonTV (16 eps)Dec 2020 - Mar 20211,882,760 membersManga StoreVolume 1€10.99Preview",8.80,16,Dec,2020
35,36,"Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 2021 - Feb 20221,302,152 members",8.79,11,Dec,2021
36,37,"Kizumonogatari III: Reiketsu-henMovie (1 eps)Jan 2017 - Jan 2017445,640 membersManga StorePart1€9.99Preview",8.79,1,Jan,2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,856 members",8.79,11,Apr,2023
38,39,"Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members",8.78,10,Oct,2016
39,40,"Sen to Chihiro no KamikakushiMovie (1 eps)Jul 2001 - Jul 20011,784,960 members",8.78,1,Jul,2001
40,41,"Monogatari Series: Second SeasonTV (26 eps)Jul 2013 - Dec 2013653,257 membersManga StoreVolume 1€9.99Preview",8.77,26,Jul,2013
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77,12,Jan,2022
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76,75,Oct,2000
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,796,109 members",8.75,26,Apr,1998
44,45,"Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members",8.75,26,Apr,2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview",8.74,24,Jul,2019
46,47,"Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 2014 - Dec 2014257,622 membersManga StoreVolume 1€10.99Preview",8.73,10,Oct,2014
47,48,"Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV (12 eps)Jan 2017 - Mar 2017182,450 membersManga StoreVolume 1€12.99Preview",8.72,12,Jan,2017
48,49,"Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 2022600,098 members",8.71,12,Oct,2022
49,50,"Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henO VA (4 eps)Feb 1999 - Sep 1999271,108 members",8.71,4,Feb,1999

In [20]:
#---------------------EXTRACTING END MONTH-------------------#

#------UNDERSTANDING PATTERN-----------#

display(df.loc[[1,11,21,31,41]])

# we can see end timestamp starts after dash and 
# ends 6 digits before ' members'

,Rank,Title,Score,Episode_Count,Start_Month,Start_Year
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24,Apr,2011
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,110,Jan,1988
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89,1,Sep,2020
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81,12,Jan,2018
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77,12,Jan,2022

In [21]:
#--------------------END TIMESTAMP DEBUGGING------------------------#


def get_time_year(title):

    start = title.find(')')
    end   = title.find(' members')

    time_stamp = title[start:end]
    print("time_stamp           : ",time_stamp)

    time_stamp = title[start+1:end-7]
    print("Corrected Time Stamp : ",time_stamp)
    

    parts = time_stamp.strip() # removing leading / trailing spaces
    parts = time_stamp.split(' ')
    # for end year we have to slice part[4] to first 4 characters 
    parts[4] = parts[4][0:4]
    print("Parts: ",parts)
    print("\n")

    
    return parts[4]
    

threshold = np.arange(0,11)
display(df.loc[threshold]['Title'].apply(get_time_year))

time_stamp           :  )Apr 2009 - Jul 20103,218,472
Corrected Time Stamp :  Apr 2009 - Jul 20103,
Parts:  ['Apr', '2009', '-', 'Jul', '2010']


time_stamp           :  )Apr 2011 - Sep 20112,473,707
Corrected Time Stamp :  Apr 2011 - Sep 20112,
Parts:  ['Apr', '2011', '-', 'Sep', '2011']


time_stamp           :  )Oct 2022 - Dec 2022474,138
Corrected Time Stamp :  Oct 2022 - Dec 2022
Parts:  ['Oct', '2022', '-', 'Dec', '2022']


time_stamp           :  )Apr 2015 - Mar 2016605,113
Corrected Time Stamp :  Apr 2015 - Mar 2016
Parts:  ['Apr', '2015', '-', 'Mar', '2016']


time_stamp           :  )Apr 2019 - Jul 20192,146,679
Corrected Time Stamp :  Apr 2019 - Jul 20192,
Parts:  ['Apr', '2019', '-', 'Jul', '2019']


time_stamp           :  )Apr 2011 - Mar 2012534,105
Corrected Time Stamp :  Apr 2011 - Mar 2012
Parts:  ['Apr', '2011', '-', 'Mar', '2012']


time_stamp           :  )Jan 2021 - Jan 2021137,208
Corrected Time Stamp :  Jan 2021 - Jan 2021
Parts:  ['Jan', '2021', '-', 'Jan', '2021']


time_stamp           :  )Oct 2011 - Sep 20142,701,154
Corrected Time Stamp :  Oct 2011 - Sep 20142,
Parts:  ['Oct', '2011', '-', 'Sep', '2014']


time_stamp           :  )Apr 2022 - Jun 2022851,445
Corrected Time Stamp :  Apr 2022 - Jun 2022
Parts:  ['Apr', '2022', '-', 'Jun', '2022']


time_stamp           :  )Oct 2012 - Mar 2013313,446
Corrected Time Stamp :  Oct 2012 - Mar 2013
Parts:  ['Oct', '2012', '-', 'Mar', '2013']


time_stamp           :  )Mar 2023 - May 2023472,340
Corrected Time Stamp :  Mar 2023 - May 2023
Parts:  ['Mar', '2023', '-', 'May', '2023']

0     2010
1     2011
2     2022
3     2016
4     2019
5     2012
6     2021
7     2014
8     2022
9     2013
10    2023
Name: Title, dtype: object

In [22]:
#-----------------CREATING NEW COLUMN FOR END YEAR-----------#

#-------Removing prints for calling every row of dataframe----------#

def get_time_year(title):

    start = title.find(')')
    end   = title.find(' members')

    time_stamp = title[start:end]
    

    time_stamp = title[start+1:end-7]
    

    parts = time_stamp.strip() # removing leading / trailing spaces
    parts = time_stamp.split(' ')
    # for end year we have to slice part[4] to first 4 characters 
    parts[4] = parts[4][0:4]

    
    return parts[4]

df['End_Year'] = df['Title'].apply(get_time_year)

df.head()

,Rank,Title,Score,Episode_Count,Start_Month,Start_Year,End_Year
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,64,Apr,2009,2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24,Apr,2011,2011
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,13,Oct,2022,2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,51,Apr,2015,2016
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,10,Apr,2019,2019

In [23]:
#----------VIEWING FIRST 20 COLUMNS----------#

threshold = np.arange(0,20)
df.loc[threshold]

,Rank,Title,Score,Episode_Count,Start_Month,Start_Year,End_Year
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,64,Apr,2009,2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24,Apr,2011,2011
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,13,Oct,2022,2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,51,Apr,2015,2016
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,10,Apr,2019,2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,51,Apr,2011,2012
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,1,Jan,2021,2021
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,148,Oct,2011,2014
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,13,Apr,2022,2022
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,13,Oct,2012,2013
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,2,Mar,2023,2023
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,110,Jan,1988,1997
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,13,Jul,2023,2023
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,13,Apr,2021,2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,12,Jan,2017,2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,201,Apr,2006,2010
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,1,Sep,2016,2016
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,22,Oct,2017,2018
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,24,Oct,2008,2009
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,25,Apr,2008,2008

In [24]:
#-----------VIEWING COMPLETE DATAFRAME--------#
display(df)

,Rank,Title,Score,Episode_Count,Start_Month,Start_Year,End_Year
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,64,Apr,2009,2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24,Apr,2011,2011
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,13,Oct,2022,2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,51,Apr,2015,2016
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,10,Apr,2019,2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,51,Apr,2011,2012
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,1,Jan,2021,2021
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,148,Oct,2011,2014
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,13,Apr,2022,2022
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,13,Oct,2012,2013
10,11,"Shingeki no Kyojin: The Final Season - Kanketsu-henSpecial (2 eps)Mar 2023 - May 2023472,340 membersManga StoreVolume 1€10.99Preview",9.03,2,Mar,2023,2023
11,12,"Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members",9.02,110,Jan,1988,1997
12,13,"Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (13 eps)Jul 2023 - Aug 2023 178,482 members",8.99,13,Jul,2023,2023
13,14,"Fruits Basket: The FinalTV (13 eps)Apr 2021 - Jun 2021443,882 membersManga StoreVolume 1€6.66Preview",8.99,13,Apr,2021,2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 members",8.98,12,Jan,2017,2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,418 members",8.94,201,Apr,2006,2010
16,17,"Koe no KatachiMovie (1 eps)Sep 2016 - Sep 20162,228,957 membersManga StoreVolume 1€10.99Preview",8.94,1,Sep,2016,2016
17,18,"3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 - Mar 2018388,358 members",8.93,22,Oct,2017,2018
18,19,"Clannad: After StoryTV (24 eps)Oct 2008 - Mar 20091,160,879 members",8.93,24,Oct,2008,2009
19,20,"Code Geass: Hangyaku no Lelouch R2TV (25 eps)Apr 2008 - Sep 20081,720,715 members",8.91,25,Apr,2008,2008
20,21,"Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien NareMovie (1 eps)Jul 2013 - Jul 2013232,388 members",8.91,1,Jul,2013,2013
21,22,"Violet Evergarden MovieMovie (1 eps)Sep 2020 - Sep 2020564,225 members",8.89,1,Sep,2020,2020
22,23,"Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 - Aug 2017385,248 members",8.88,7,Aug,2017,2017
23,24,"Gintama.: Shirogane no Tamashii-hen - Kouhan-senTV (14 eps)Jul 2018 - Oct 2018189,172 members",8.88,14,Jul,2018,2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081 members",8.87,74,Apr,2004,2005
25,26,"Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 20162,635,814 membersManga StoreVolume 1€4.58Preview",8.84,1,Aug,2016,2016
26,27,"Kaguya-sama wa Kokurasetai: First Kiss wa OwaranaiMovie (1 eps)Dec 2022 - Dec 2022205,150 members",8.84,1,Dec,2022,2022
27,28,"Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022464,981 members",8.83,12,Oct,2022,2022
28,29,"The First Slam DunkMovie (1 eps)Dec 2022 - Dec 202227,063 members",8.83,1,Dec,2022,202
29,30,"Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun 2023495,454 membersManga StoreVolume 1€17.99Preview",8.82,24,Jan,2023,2023
30,31,"Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 - Aug 2023 556,301 members",8.82,23,Jul,2023,2023
31,32,"Gintama.: Shirogane no Tamashii-henTV (12 eps)Jan 2018 - Mar 2018203,540 members",8.81,12,Jan,2018,2018
32,33,"Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 202193,645 members",8.81,26,Apr,2020,202
33,34,"Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 20191,458,089 members",8.80,13,Jan,2019,2019
34,35,"Shingeki no Kyojin: The Final SeasonTV (16 eps)Dec 2020 - Mar 20211,882,760 membersManga StoreVolume 1€10.99Preview",8.80,16,Dec,2020,2021
35,36,"Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 2021 - Feb 20221,302,152 members",8.79,11,Dec,2021,2022
36,37,"Kizumonogatari III: Reiketsu-henMovie (1 eps)Jan 2017 - Jan 2017445,640 membersManga StorePart1€9.99Preview",8.79,1,Jan,2017,2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,856 members",8.79,11,Apr,2023,2023
38,39,"Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen KoukouTV (10 eps)Oct 2016 - Dec 20161,157,497 members",8.78,10,Oct,2016,2016
39,40,"Sen to Chihiro no KamikakushiMovie (1 eps)Jul 2001 - Jul 20011,784,960 members",8.78,1,Jul,2001,2001
40,41,"Monogatari Series: Second SeasonTV (26 eps)Jul 2013 - Dec 2013653,257 membersManga StoreVolume 1€9.99Preview",8.77,26,Jul,2013,2013
41,42,"Shingeki no Kyojin: The Final Season Part 2TV (12 eps)Jan 2022 - Apr 20221,170,165 membersManga StoreVolume 1€10.99Preview",8.77,12,Jan,2022,2022
42,43,"Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members",8.76,75,Oct,2000,2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,796,109 members",8.75,26,Apr,1998,1999
44,45,"Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 202255,833 members",8.75,26,Apr,2022,202
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,403,669 membersManga StoreVolume 1€17.99Preview",8.74,24,Jul,2019,2019
46,47,"Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 2014 - Dec 2014257,622 membersManga StoreVolume 1€10.99Preview",8.73,10,Oct,2014,2014
47,48,"Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-henTV (12 eps)Jan 2017 - Mar 2017182,450 membersManga StoreVolume 1€12.99Preview",8.72,12,Jan,2017,2017
48,49,"Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 2022600,098 members",8.71,12,Oct,2022,2022
49,50,"Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henO VA (4 eps)Feb 1999 - Sep 1999271,108 members",8.71,4,Feb,1999,1999

In [25]:
#--------------EXTRACTING END MONTH DEBUGING--------------#

def get_end_month(title):

    start = title.find(')')
    end   = title.find(' members')

    time_stamp = title[start:end]
    

    time_stamp = title[start+1:end-7]
    

    parts = time_stamp.strip() # removing leading / trailing spaces
    parts = time_stamp.split(' ')
    # for end year we have to slice part[4] to first 4 characters 
    parts[4] = parts[4][0:4]

    
    return parts[3]

df.loc[[1,2,3,4,5,32,42]]['Title'].apply(get_end_month)

# df['End_Month'] = df['Title'].apply(get_end_month)

1     Sep
2     Dec
3     Mar
4     Jul
5     Mar
32    Oct
42    Mar
Name: Title, dtype: object

In [26]:
#------------------APPLYING FUNCTION------------------#

df['End_Month'] = df['Title'].apply(get_end_month)
df.head()

,Rank,Title,Score,Episode_Count,Start_Month,Start_Year,End_Year,End_Month
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,64,Apr,2009,2010,Jul
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24,Apr,2011,2011,Sep
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,13,Oct,2022,2022,Dec
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,51,Apr,2015,2016,Mar
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,10,Apr,2019,2019,Jul

In [27]:
# 3--> which anime has the highest score
# 4--> give me top 5 highest scoring anime
# 5--> which anime has the highest episode count
# 6--> animes with top 5 episode count
# 7--> which is the longest running anime

In [38]:
#--------------------Q:3---------------------#

# highest score for any anime

max_score = df['Score'].max()
display(max_score)

# which index had the highest score 

# ( first index with score 9.1 will be here )
# if there are many anime with score as max score ALL OF THEM WILL NOT BE SHOWN BY THIS...
max_score_index = df['Score'].idxmax(axis=0)
display(max_score_index)

# row with the max_index i.e max score
max_score_row = df.loc[[max_score_index]]
display(max_score_row)

np.float64(9.1)

0

,Rank,Title,Score,Episode_Count,Start_Month,Start_Year,End_Year,End_Month
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.1,64,Apr,2009,2010,Jul

In [46]:
#------------------------Q:4-------------------------------------#

# here first appearance of 9.1 is shown for multiple anime with same max score ( rank 1) we use sorting 
df_sorted_by_score = df.sort_values(by='Score',ascending=False)
display(df_sorted_by_score.head(10)) # top 10 by score 


# View title and score of top 5 anime by score...
df_sorted_by_score = df.sort_values(by='Score',ascending=False)
display(df_sorted_by_score['Title'.head(5))

,Rank,Title,Score,Episode_Count,Start_Month,Start_Year,End_Year,End_Month
0,1,"Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview",9.10,64,Apr,2009,2010,Jul
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members",9.07,24,Apr,2011,2011,Sep
2,3,"Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members",9.06,13,Oct,2022,2022,Dec
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members",9.06,51,Apr,2015,2016,Mar
4,5,"Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview",9.05,10,Apr,2019,2019,Jul
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 members",9.04,51,Apr,2011,2012,Mar
6,7,"Gintama: The FinalMovie (1 eps)Jan 2021 - Jan 2021137,208 members",9.04,1,Jan,2021,2021,Jan
7,8,"Hunter x Hunter TV (148 eps)Oct 2011 - Sep 20142,701,154 members",9.04,148,Oct,2011,2014,Sep
8,9,"Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members",9.04,13,Apr,2022,2022,Jun
9,10,"Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2013313,446 members",9.03,13,Oct,2012,2013,Mar

KeyError: 'Score'